# PostgreSQL DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_reservation_db
spring.datasource.username=postgres
spring.datasource.password=N@ndu123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true

# Redis Config
spring.redis.host=localhost
spring.redis.port=6379

booking.lock.hold-duration-minutes=1


#ServerPort
server.port=8080